---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: policyfile_zero
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[serverbox::default]
    attributes:
